openapi: 3.0.0
info:
  title: NetSchool
  description: The API for the NetSchool irTech project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/LEBEDEVKM/NetSchool/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://188.226.50.152/webapi
  description: NetCity Yekateringurg
paths:
  /student/diary:
    get:
      tags:
      - student
      description: returns all assignments
      operationId: studentDiary
      parameters:
      - name: studentId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: weekStart
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      - name: weekEnd
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      - name: withLaAssigns
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: withPastMandatory
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: yearId
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: All the prepareloginform
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diary'
  /logindata:
    get:
      tags:
      - login
      description: returns all login data
      operationId: logindata
      responses:
        "200":
          description: All the login data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginData'
  /prepareloginform:
    get:
      tags:
      - login
      description: returns all prepareloginform
      operationId: prepareloginform
      parameters:
      - name: cacheVer
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: All the prepareloginform
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrepareLoginForm'
  /prepareemloginform:
    get:
      tags:
      - login
      description: returns all prepareemloginform
      operationId: prepareemloginform
      parameters:
      - name: cacheVer
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: All the prepareemloginform
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrepareEmLoginForm'
components:
  schemas:
    Mark:
      type: object
      properties:
        assignmentId:
          type: integer
        studentId:
          type: integer
        mark:
          type: integer
        dutyMark:
          type: boolean
      example:
        studentId: 1
        assignmentId: 6
        dutyMark: true
        mark: 5
    Attachment:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        originalFileName:
          type: string
        description:
          type: string
      example:
        originalFileName: originalFileName
        name: name
        description: description
        id: 5
    DiaryAssignment:
      type: object
      properties:
        mark:
          $ref: '#/components/schemas/Mark'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        id:
          type: integer
        typeId:
          type: integer
        assignmentName:
          type: string
        weight:
          type: integer
        dueDate:
          type: string
          format: date
        classMeetingId:
          type: integer
        existsTestPlan:
          type: boolean
      example:
        existsTestPlan: true
        attachments:
        - originalFileName: originalFileName
          name: name
          description: description
          id: 5
        - originalFileName: originalFileName
          name: name
          description: description
          id: 5
        dueDate: 2000-01-23
        weight: 9
        typeId: 7
        classMeetingId: 3
        id: 2
        mark:
          studentId: 1
          assignmentId: 6
          dutyMark: true
          mark: 5
        assignmentName: assignmentName
    DiaryLesson:
      type: object
      properties:
        classmeetingId:
          type: string
        day:
          type: string
          format: date
        number:
          type: integer
        room:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        subjectName:
          type: string
        assignments:
          type: array
          items:
            $ref: '#/components/schemas/DiaryAssignment'
      example:
        number: 0
        assignments:
        - existsTestPlan: true
          attachments:
          - originalFileName: originalFileName
            name: name
            description: description
            id: 5
          - originalFileName: originalFileName
            name: name
            description: description
            id: 5
          dueDate: 2000-01-23
          weight: 9
          typeId: 7
          classMeetingId: 3
          id: 2
          mark:
            studentId: 1
            assignmentId: 6
            dutyMark: true
            mark: 5
          assignmentName: assignmentName
        - existsTestPlan: true
          attachments:
          - originalFileName: originalFileName
            name: name
            description: description
            id: 5
          - originalFileName: originalFileName
            name: name
            description: description
            id: 5
          dueDate: 2000-01-23
          weight: 9
          typeId: 7
          classMeetingId: 3
          id: 2
          mark:
            studentId: 1
            assignmentId: 6
            dutyMark: true
            mark: 5
          assignmentName: assignmentName
        startTime: startTime
        endTime: endTime
        classmeetingId: classmeetingId
        day: 2000-01-23
        room: room
        subjectName: subjectName
    DiaryWeekDays:
      type: object
      properties:
        date:
          type: string
          format: date
        lessons:
          type: array
          items:
            $ref: '#/components/schemas/DiaryLesson'
      example:
        date: 2000-01-23
        lessons:
        - number: 0
          assignments:
          - existsTestPlan: true
            attachments:
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            dueDate: 2000-01-23
            weight: 9
            typeId: 7
            classMeetingId: 3
            id: 2
            mark:
              studentId: 1
              assignmentId: 6
              dutyMark: true
              mark: 5
            assignmentName: assignmentName
          - existsTestPlan: true
            attachments:
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            dueDate: 2000-01-23
            weight: 9
            typeId: 7
            classMeetingId: 3
            id: 2
            mark:
              studentId: 1
              assignmentId: 6
              dutyMark: true
              mark: 5
            assignmentName: assignmentName
          startTime: startTime
          endTime: endTime
          classmeetingId: classmeetingId
          day: 2000-01-23
          room: room
          subjectName: subjectName
        - number: 0
          assignments:
          - existsTestPlan: true
            attachments:
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            dueDate: 2000-01-23
            weight: 9
            typeId: 7
            classMeetingId: 3
            id: 2
            mark:
              studentId: 1
              assignmentId: 6
              dutyMark: true
              mark: 5
            assignmentName: assignmentName
          - existsTestPlan: true
            attachments:
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            dueDate: 2000-01-23
            weight: 9
            typeId: 7
            classMeetingId: 3
            id: 2
            mark:
              studentId: 1
              assignmentId: 6
              dutyMark: true
              mark: 5
            assignmentName: assignmentName
          startTime: startTime
          endTime: endTime
          classmeetingId: classmeetingId
          day: 2000-01-23
          room: room
          subjectName: subjectName
    Diary:
      type: object
      properties:
        weekStart:
          type: string
        weekEnd:
          type: string
        weekDays:
          type: array
          items:
            $ref: '#/components/schemas/DiaryWeekDays'
        termName:
          type: string
        className:
          type: string
      example:
        weekStart: weekStart
        weekDays:
        - date: 2000-01-23
          lessons:
          - number: 0
            assignments:
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            startTime: startTime
            endTime: endTime
            classmeetingId: classmeetingId
            day: 2000-01-23
            room: room
            subjectName: subjectName
          - number: 0
            assignments:
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            startTime: startTime
            endTime: endTime
            classmeetingId: classmeetingId
            day: 2000-01-23
            room: room
            subjectName: subjectName
        - date: 2000-01-23
          lessons:
          - number: 0
            assignments:
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            startTime: startTime
            endTime: endTime
            classmeetingId: classmeetingId
            day: 2000-01-23
            room: room
            subjectName: subjectName
          - number: 0
            assignments:
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            startTime: startTime
            endTime: endTime
            classmeetingId: classmeetingId
            day: 2000-01-23
            room: room
            subjectName: subjectName
        weekEnd: weekEnd
        className: className
        termName: termName
    PrepareEmLoginForm:
      type: object
      properties:
        countries:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        states:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        hlevels:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        ems:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        em_cid:
          type: integer
        em_sid:
          type: integer
        hlevel:
          type: integer
        emId:
          type: integer
      example:
        em_cid: 0
        em_sid: 6
        hlevel: 1
        ems:
        - null
        - null
        countries:
        - name: name
          id: 0
        - name: name
          id: 0
        emId: 5
        hlevels:
        - null
        - null
        states:
        - null
        - null
    PrepareLoginForm:
      type: object
      properties:
        countries:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        states:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        provinces:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        cities:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        funcs:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        schools:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        cid:
          type: integer
        sid:
          type: integer
        pid:
          type: integer
        cn:
          type: integer
        sft:
          type: integer
        scid:
          type: integer
        hlevels:
          type: object
        ems:
          type: object
      example:
        sft: 2
        provinces:
        - null
        - null
        cities:
        - null
        - null
        pid: 5
        ems: {}
        countries:
        - name: name
          id: 0
        - name: name
          id: 0
        cn: 5
        hlevels: {}
        states:
        - null
        - null
        sid: 1
        schools:
        - null
        - null
        funcs:
        - null
        - null
        scid: 7
        cid: 6
    LoginData:
      type: object
      properties:
        productName:
          type: string
        version:
          type: string
        esiaLoginPage:
          type: string
        cacheVer:
          type: string
        schoolLogin:
          type: boolean
        emLogin:
          type: boolean
        windowsAuth:
          type: boolean
        enableSms:
          type: boolean
        esiaMainAuth:
          type: boolean
        esiaButton:
          type: boolean
        signatureLogin:
          type: boolean
      example:
        schoolLogin: true
        signatureLogin: true
        esiaLoginPage: esiaLoginPage
        esiaMainAuth: true
        cacheVer: cacheVer
        windowsAuth: true
        emLogin: true
        version: version
        productName: productName
        esiaButton: true
        enableSms: true
    PrepareEmLoginForm_countries:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        name: name
        id: 0
